import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {randomUUID} from 'node:crypto';
const require=createRequire(new URL('./package.json', import.meta.url));const {initializeApp,cert}=require('firebase-admin/app');const {getFirestore}=require('firebase-admin/firestore');const {getAuth}=require('firebase-admin/auth');initializeApp({credential:cert(JSON.parse(readFileSync(process.env.GOOGLE_APPLICATION_CREDENTIALS,'utf8'))),projectId:'bee-production-e1058'});const db=getFirestore(),auth=getAuth();const id='audit-test-'+randomUUID();const created=[];
const base='https://firestore.googleapis.com/v1/projects/bee-production-e1058/databases/(default)/documents';
async function token(uid){const r=await fetch('https://identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken?key=AIzaSyDUVCG5IX9nyWRKtbcHWDp5b0c9oJZqHWs',{method:'POST',headers:{'Content-Type':'application/json',Referer:'https://siaa-ten.vercel.app/'},body:JSON.stringify({token:await auth.createCustomToken(uid),returnSecureToken:true})});const data=await r.json();assert.ok(r.ok);return data.idToken;}
async function request(path,token,method='GET',body){return fetch(base+'/'+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body&&JSON.stringify(body)});}
async function put(collection,key,value){await db.collection(collection).doc(key).set(value);created.push([collection,key]);}
let pm;
try{pm=await auth.createUser({email:id+'@example.com'});await put('app_users',pm.uid,{id:pm.uid,full_name:'Temporary PM',role:'project_manager',disabled:false});
await put('projects',id,{id,pm:pm.uid,access_ids:[pm.uid]});await put('projects',id+'-other',{id:id+'-other',pm:'another-pm',access_ids:[]});
await put('audit_logs',id,{id,entity_type:'project',project_id:id,action:'Updated',entity:'Project',access_ids:[pm.uid]});await put('audit_logs',id+'-system',{id:id+'-system',entity_type:'system',project_id:id,action:'Updated',entity:'User',access_ids:[pm.uid]});await put('audit_logs',id+'-other',{id:id+'-other',entity_type:'project',project_id:id+'-other',access_ids:[pm.uid]});
const t=await token(pm.uid);assert.equal((await request('audit_logs/'+id,t)).status,200);assert.equal((await request('audit_logs/'+id+'-system',t)).status,403);assert.equal((await request('audit_logs/'+id+'-other',t)).status,403);assert.equal((await request('projects/'+id+'-other',t)).status,403);assert.equal((await request('audit_logs/'+id,t,'DELETE')).status,403);assert.equal((await request('audit_logs/'+id,t,'PATCH',{fields:{detail:{stringValue:'tampered'}}})).status,403);
const q=await fetch(base+':runQuery',{method:'POST',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify({structuredQuery:{from:[{collectionId:'audit_logs'}],where:{compositeFilter:{op:'AND',filters:[{fieldFilter:{field:{fieldPath:'project_id'},op:'EQUAL',value:{stringValue:id}}},{fieldFilter:{field:{fieldPath:'entity_type'},op:'EQUAL',value:{stringValue:'project'}}}]}}}})});assert.equal(q.status,200,await q.text());
await db.collection('projects').doc(id).update({pm:'replacement',access_ids:[]});assert.equal((await request('audit_logs/'+id,t)).status,403);
const admins=await db.collection('app_users').where('role','==','admin').get();const admin=admins.docs.find(d=>!d.data().disabled);assert.ok(admin);const at=await token(admin.id);assert.equal((await request('audit_logs/'+id+'-system',at)).status,200);assert.equal((await request('audit_logs/'+id+'-other',at)).status,200);console.log('PASS: PM project query, system/cross-project denial, removed-PM denial, immutable logs and system-wide Admin reads.');
}finally{for(const [c,k]of created.reverse())await db.collection(c).doc(k).delete();if(pm)await auth.deleteUser(pm.uid);console.log('Temporary permission fixtures removed.');}
