import test from 'node:test';
import assert from 'node:assert/strict';
import { createTeamInviteHandler } from '../../api/team-invite.mjs';

function fixture({configured=true,failMail=false}={}) {
  const records=new Map([['app_users/admin',{id:'admin',role:'admin',disabled:false}],['app_users/editor',{id:'editor',role:'editor',disabled:false}]]);
  const accounts=new Map(); const sent=[];
  function ref(path){return {path,id:path.split('/').at(-1),async get(){const value=records.get(path);return {id:this.id,ref:this,exists:value!==undefined,data:()=>value&&structuredClone(value)}},async create(value){assert.ok(!records.has(path));records.set(path,structuredClone(value))},async set(value,options){records.set(path,options?.merge?{...records.get(path),...value}:structuredClone(value))},async update(value){assert.ok(records.has(path));records.set(path,{...records.get(path),...value})}};}
  const batch=()=>{const writes=[];return {update(r,v){writes.push(()=>r.update(v))},set(r,v,o){writes.push(()=>r.set(v,o))},async commit(){for(const write of writes)await write()}}};
  const db={collection(name){return {doc:id=>ref(name+'/'+id),where(field,op,value){return {async get(){return {docs:await Promise.all([...records].filter(([path,data])=>path.startsWith(name+'/')&&data[field]===value).map(([path])=>ref(path).get()))}}}}}},batch,async runTransaction(fn){return fn({get:r=>r.get(),set:(r,v)=>r.set(v)})}};
  const auth={async verifyIdToken(token){if(!['admin','editor','member','unverified'].includes(token))throw Error('Invalid');return {uid:token==='unverified'?'member':token,email_verified:token!=='unverified',firebase:{sign_in_provider:'password'}}},async getUserByEmail(email){const found=[...accounts.values()].find(user=>user.email===email);if(found)return found;throw Object.assign(Error('Missing'),{code:'auth/user-not-found'})},async createUser(input){const user={...input,uid:'member'};accounts.set(user.uid,user);return user},async deleteUser(uid){accounts.delete(uid)},async getUser(uid){return accounts.get(uid)},async generateEmailVerificationLink(){return 'https://example.invalid/verify?oobCode=private-verify'},async generatePasswordResetLink(){return 'https://example.invalid/reset?oobCode=private-reset'}};
  const handler=createTeamInviteHandler({auth,db,configured,sendMail:async params=>{if(failMail)throw Error('provider failure');sent.push(params)}});
  async function request(body,token='admin'){const res={headers:{},status(code){this.code=code;return this},setHeader(k,v){this.headers[k]=v},json(data){this.data=data;return this},end(){return this}};await handler({method:'POST',headers:token?{authorization:'Bearer '+token}:{},body},res);return res;}
  return {records,accounts,sent,request};
}
const invite={action:'invite',name:'Test Member',email:'member@example.com',role:'editor'};
test('anonymous and non-admin callers cannot create invitations',async()=>{for(const token of [null,'editor','bad']){const f=fixture();const result=await f.request(invite,token);assert.ok([401,403].includes(result.code));assert.equal(f.accounts.size,0);assert.equal(f.sent.length,0)}});
test('missing service configuration prevents account creation',async()=>{const f=fixture({configured:false});assert.equal((await f.request(invite)).code,503);assert.equal(f.accounts.size,0)});
test('invitation saves profile and history without passwords or action links',async()=>{const f=fixture();const result=await f.request(invite);assert.equal(result.code,200);assert.equal(result.data.email_sent,true);assert.equal(f.sent.length,1);const profile=f.records.get('app_users/member');assert.equal(profile.role,'editor');assert.equal(profile.verification_required,true);assert.equal(profile.invitation_status,'sent');assert.equal(f.records.get('team_invitations/member').invitation_status,'sent');assert.ok(f.accounts.get('member').password.length>=32);for(const value of [profile,result.data,f.records.get('team_invitations/member')]){assert.equal(JSON.stringify(value).includes('private-reset'),false);assert.equal(JSON.stringify(value).includes(f.accounts.get('member').password),false)}assert.equal(f.sent[0].to_email,'member@example.com');assert.match(f.sent[0].verification_link,/verify/)});
test('mail failures preserve the member and allow explicit retry',async()=>{const f=fixture({failMail:true});const result=await f.request(invite);assert.equal(result.code,200);assert.equal(result.data.email_sent,false);assert.equal(f.records.get('app_users/member').invitation_status,'failed');assert.equal(f.records.get('team_invitations/member').invitation_status,'failed');assert.equal(f.accounts.size,1)});
test('duplicate email does not overwrite or promote the account',async()=>{const f=fixture();await f.request(invite);assert.equal((await f.request({...invite,role:'admin'})).code,409);assert.equal(f.records.get('app_users/member').role,'editor');assert.equal(f.sent.length,1)});
test('resending has a cooldown',async()=>{const f=fixture();await f.request(invite);assert.equal((await f.request({action:'resend',uid:'member'})).code,429);assert.equal(f.sent.length,1)});
test('verification uses Firebase ownership, then password sign-in activates invitation',async()=>{const f=fixture();await f.request(invite);assert.equal((await f.request({action:'accept'},'unverified')).code,403);assert.equal(f.records.get('app_users/member').invitation_status,'sent');f.accounts.get('member').emailVerified=true;assert.equal((await f.request({action:'refresh'})).code,200);assert.equal(f.records.get('app_users/member').invitation_status,'verified');assert.equal((await f.request({action:'accept'},'member')).code,200);assert.equal(f.records.get('app_users/member').invitation_status,'accepted');assert.ok(f.records.get('team_invitations/member').accepted_at)});
